name: Test
on:
  push:
    tags:
      - v*
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    env:
      TEST_DIR: e2e_test
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v5
        with:
          go-version: 1.21
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - name: Verify dependencies
        run: go mod verify
      - name: Build
        run: go build -v ./...
      - name: Vet
        run: go vet -v ./...
      - name: Test
        run: go test -v -count=1 -shuffle=on -timeout=30m -race ./...
      - name: E2E-Vet
        run: cd "$TEST_DIR" && go vet -v ./...
      - name: E2E-Test
        run: cd "$TEST_DIR" && go test -v -count=1 -shuffle=on -timeout=30m -race ./...
